apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jqmt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jqmt
    app.kubernetes.io/part-of: byoc-app-unaa
  name: jqmt
spec:
  rules:
  - host: jqmt-byoc-vsrs-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-86kzv.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: jqmt
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
